all:
	make -B DEBUG="n" -C ../generator
	make -B DEBUG="n" -C ../serial
	make -B DEBUG="n" -C ../cilk
	make -B DEBUG="n" -C ../cilkplus



debug:
	make -B -C ../generator
	make -B -C ../serial
	make -B -C ../cilk
	make -B -C ../cilkplus
